/**
 * commands.ts — Slash commands for the orchestrator.
 *
 * /summoner [task] — triggers the full orchestrator workflow (Scout → Plan → Crafter → Gatekeeper)
 * /summon <agent> [task]  — triggers a single agent tool call (nudges LLM)
 * /watch  <agent>         — read-only live feed of agent activity
 * /back                    — return from watch mode to Main Agent view
 *
 * @see docs/prd.md §5.2 — Watch mode
 * @see docs/plan.md Phase 6
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { getRegisteredAgents } from "./agents";
import { agentActivityLog } from "./state";

// ── Command Registration ──────────────────────────────────────────────────

export function registerCommands(pi: ExtensionAPI): void {
  // /summoner — full orchestrator workflow
  pi.registerCommand("summoner", {
    description: "Launch the full orchestrator workflow: Scout → Plan → Crafter → Gatekeeper",
    handler: async (args, ctx) => {
      const task = args?.trim() || "the current task";

      // Send a user message that the LLM will immediately act on.
      // This triggers the actual workflow — the LLM reads this and starts calling tools.
      pi.sendUserMessage(
        `🏰 **Agent Summoner workflow initiated.**

` +
        `**Task:** ${task}

` +
        `Follow this workflow step by step. Do NOT just describe it — actually call the tools.

` +
        `## Step 1 — Scout
` +
        `Call \`summon_scout\` now to map dependencies. Determine the scope from the task.
` +
        `Provide a JSON object: { "scope": "<dir>", "pattern": "<optional symbol>" }

` +
        `## Step 2 — Plan
` +
        `After Scout returns, present the execution plan to the user:
` +
        `- Show the phase breakdown (which files in which order, parallel-safety notes)
` +
        `- Flag any risks (low confidence, circular dependencies)
` +
        `- Present trust mode options: 🙈 Trust or 🔍 Checkpoint
` +
        `- **STOP and ASK the user:** "Does this plan look good? Anything you want to change?"

` +
        `### Approval gate (MANDATORY):
` +
        `- If the user approves: call \`set_trust_mode\` with their trust choice.
` +
        `- If the user wants changes: update the plan based on their feedback. Re-invoke Scout if scope changed. Present revised plan and ask again.
` +
        `- Do NOT proceed to execution until the user explicitly approves the plan.

` +
        `### Write PLAN.md:
` +
        `After approval, create a \`PLAN.md\` file (or \`.pi/plan.md\`) in the project root with:
` +
        `
` +
        `# Plan: <task summary>
` +
        `## Requirements
` +
        `- <list each requirement>
` +
        `## Scope
` +
        `- Directory and files affected
` +
        `## Execution Plan
` +
        `### Phase N (parallel-safe / serial)
` +
        `- [ ] \`file.ts\` — <instruction>
` +
        `## ⚠️ Risks  |  ## Trust Mode  |  ## 🔄 Circular Dependencies
` +
        `
` +
        `Use checkbox format \`- [ ]\` for pending, \`- [x]\` for done.
` +
        `Include a footer: "*Generated by Agent Summoner | <timestamp>*"

` +
        `## Step 3 — Execute
` +
        `Summon \`summon_crafter\` for each file in each phase. Same-phase files can run in parallel.
` +
        `If Phase 0 is needed (new deps), call \`summon_crafter_dep_install\` first.
` +
        `Unplanned file discovery: check the Ledger, approve if no conflict, wait if blocked.
` +
        `**After EACH phase completes, update PLAN.md:**
` +
        `- Check off completed files: change \`- [ ]\` to \`- [x]\` for done items
` +
        `- Add any discovered (unplanned) files to the plan
` +
        `- If requirements changed mid-way: update the Requirements section but KEEP completed checkboxes
` +
        `- Update the timestamp

` +
        `Unplanned file discovery: check the Ledger, approve if no conflict, wait if blocked.

` +
        `## Step 4 — Verify
` +
        `Call \`summon_gatekeeper\` with { "phase": "baseline" } BEFORE any edits.
` +
        `After all edits, call \`summon_gatekeeper\` with { "phase": "verify" }.
` +
        `Out-of-scope failures: ALWAYS ask the user before fixing.

` +
        `## Step 5 — Report
` +
        `Walk the Ledger and present the final report.
` +
        `Update PLAN.md with final status — all checkboxes should be \`- [x]\` or \`- [ ] ❌\` for failed.

` +
        `---
` +
        `**Start now.** Call summon_scout for Step 1.`,
      );
    },
  });

  // /summon — trigger an agent
  pi.registerCommand("summon", {
    description: "Summon an agent for a task",
    getArgumentCompletions: (prefix: string) => {
      const agents = getRegisteredAgents();
      if (!prefix) return agents.map((a) => ({ value: a, label: a }));
      return agents
        .filter((a) => a.startsWith(prefix))
        .map((a) => ({ value: a, label: a }));
    },
    handler: async (args, ctx) => {
      const parts = args ? args.trim().split(/\s+/) : [];
      if (parts.length === 0) {
        const agents = getRegisteredAgents();
        const msg = agents.length > 0
          ? `Available agents: ${agents.join(", ")}`
          : "No agents registered.";
        ctx.ui.notify(msg, "info");
        return;
      }

      const agentName = parts[0];
      const registered = getRegisteredAgents();
      if (!registered.includes(agentName)) {
        ctx.ui.notify(
          `Unknown agent "${agentName}". Available: ${registered.join(", ")}`,
          "error",
        );
        return;
      }

      const task = parts.slice(1).join(" ") || "Execute task";
      ctx.ui.notify(
        `Summoning ${agentName}... Use summon_${agentName} tool with task: "${task}"`,
        "info",
      );
    },
  });

  // /watch — live agent feed (read-only)
  pi.registerCommand("watch", {
    description: "Read-only live view of a summoned agent's activity",
    getArgumentCompletions: (_prefix: string) => {
      const active: string[] = [];
      for (const [, activity] of agentActivityLog) {
        if (activity.status === "active" || activity.status === "waiting") {
          active.push(activity.agentName || "unknown");
        }
      }
      if (active.length === 0) return [{ value: "", label: "No active agents" }];
      return active.map((a) => ({ value: a, label: a }));
    },
    handler: async (args, ctx) => {
      const agentName = args?.trim();
      if (!agentName) {
        const active: Array<{ name: string; status: string; file?: string }> = [];
        for (const [, activity] of agentActivityLog) {
          if (activity.status === "active" || activity.status === "waiting") {
            active.push({
              name: activity.agentName,
              status: activity.status,
              file: activity.currentFile,
            });
          }
        }
        if (active.length === 0) {
          ctx.ui.notify("No active agents to watch.", "info");
          return;
        }
        const list = active
          .map((a) => `  ${a.status === "active" ? "🟢" : "🟡"} ${a.name}${a.file ? ` — ${a.file}` : ""}`)
          .join("\n");
        ctx.ui.notify(`Watchable agents:\n${list}\n\nUse /watch <name> to watch one.`, "info");
        return;
      }

      const agentId = [...agentActivityLog.keys()].find(
        (id) => agentActivityLog.get(id)?.agentName === agentName,
      );

      if (!agentId) {
        ctx.ui.notify(`Agent "${agentName}" not found or not active.`, "error");
        return;
      }

      // Show live feed via a simple panel
      // Full TUI takeover requires @earendil-works/pi-tui — for now, notify with current state
      const activity = agentActivityLog.get(agentId);
      if (activity) {
        const icon =
          activity.status === "active" ? "🟢" :
          activity.status === "waiting" ? "🟡" :
          activity.status === "done" ? "✅" :
          activity.status === "failed" ? "❌" : "⏳";

        const lines = [
          `Watch: ${agentName} (read-only)`,
          `${icon} Status: ${activity.status}`,
          activity.currentFile ? `   File: ${activity.currentFile}` : "",
          activity.detail ? `   ${activity.detail}` : "",
          "",
          "Use /watch again to refresh, or continue working.",
        ].filter(Boolean);

        ctx.ui.notify(lines.join("\n"), "info");
      }
    },
  });

  // /back — return from watch mode
  pi.registerCommand("back", {
    description: "Return from watch mode to Main Agent view",
    handler: async (_args, ctx) => {
      ctx.ui.notify("Returned to Main Agent.", "info");
    },
  });
}
