/**
 * plan-file.ts — Plan file writer for persistent, updateable task plans.
 *
 * Writes a structured plan to .pi/bulletin/<timestamp>.md with:
 *   - Requirements / scope / execution phases
 *   - Checkbox todo list (completed items preserved, never deleted)
 *   - Risk notes and trust mode
 *
 * The LLM creates this file after plan approval and updates it as phases
 * complete. Each task gets its own timestamped file — no overwrites.
 *
 * @see commands.ts — /summoner workflow instructions
 */

import { join } from "node:path";
import type { Plan } from "./planner";
import { getLedger } from "./ledger";
import { getTrustMode } from "./state";

// ── Plan File Path ───────────────────────────────────────────────────────

/**
 * Generate the plan file path: .pi/bulletin/<slug>_<timestamp>.md
 * Uses ISO timestamp with colons replaced for filesystem safety.
 */
export function planFilePath(cwd: string, slug?: string): string {
  const ts = new Date()
    .toISOString()
    .replace(/:/g, "-")
    .replace(/\..+/, "")
    .replace("T", "_");
  const name = slug ? `${slug}_${ts}` : ts;
  return join(cwd, ".pi", "bulletin", `${name}.md`);
}

/**
 * Generate a slug from the user's task description.
 * Converts to lowercase, replaces non-alphanumeric with hyphens, truncates to 40 chars.
 */
export function generatePlanSlug(task: string): string {
  const slug = task
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40)
    .replace(/-$/, "");

  return slug || "untitled";
}

// ── Plan File Generation ─────────────────────────────────────────────────

/**
 * Generate the full PLAN.md content.
 * Includes requirements, scope, phases with todo checkboxes, risks, and trust mode.
 *
 * @param taskSummary — one-line description of the task
 * @param plan — the execution plan (phases + risks)
 * @param scope — directory/files affected
 * @param requirements — list of requirements
 */
export function generatePlanFileContent(params: {
  taskSummary: string;
  plan: Plan;
  scope: string;
  requirements: string[];
}): string {
  const { taskSummary, plan, scope, requirements } = params;
  const ledger = getLedger();
  const trustMode = getTrustMode();
  const now = new Date().toISOString();

  const lines: string[] = [];

  // Header
  lines.push(`# Plan: ${taskSummary}`);
  lines.push("");
  lines.push(`> Generated by Agent Summoner | ${now}`);
  lines.push("");

  // Requirements
  lines.push("## Requirements");
  lines.push("");
  for (const req of requirements) {
    lines.push(`- ${req}`);
  }
  lines.push("");

  // Scope
  lines.push("## Scope");
  lines.push("");
  lines.push(`- Directory: \`${scope}\``);
  for (const phase of plan.phases) {
    for (const file of phase.files) {
      if (file !== "[Dependency Installation]") {
        lines.push(`- \`${file}\``);
      }
    }
  }
  lines.push("");

  // Execution Plan with Todo
  lines.push("## Execution Plan");
  lines.push("");

  for (const phase of plan.phases) {
    const label = phase.label || `Phase ${phase.phaseNumber}`;
    const parallel = phase.parallelSafe ? "⚡ parallel-safe" : "🔒 serial";
    lines.push(`### ${label} (${parallel})`);
    lines.push("");

    for (const file of phase.files) {
      if (file === "[Dependency Installation]") {
        lines.push(`- [ ] **Install dependencies** (\`npm install\` etc.)`);
        continue;
      }

      const entry = ledger.files[file];
      const status = entry?.status || "pending";
      const checked = status === "done" ? "x" : " ";
      const detail = entry?.summary
        ? ` — ${entry.summary}`
        : entry?.owner
          ? ` [${entry.owner}]`
          : "";

      // Always show the item. If done, checked. If failed, marked.
      const failMark = status === "failed" ? " ❌" : "";
      lines.push(`- [${checked}] \`${file}\`${detail}${failMark}`);
    }
    lines.push("");
  }

  // Discovered files (unplanned)
  const discovered = Object.entries(ledger.files).filter(
    ([, e]) => e.discovered,
  );
  if (discovered.length > 0) {
    lines.push("### 🔍 Discovered During Execution");
    lines.push("");
    for (const [file, entry] of discovered) {
      const checked = entry.status === "done" ? "x" : " ";
      lines.push(`- [${checked}] \`${file}\` *(unplanned)*`);
    }
    lines.push("");
  }

  // Risks
  if (plan.risks.length > 0) {
    lines.push("## ⚠️ Risks");
    lines.push("");
    for (const risk of plan.risks) {
      lines.push(`- ${risk}`);
    }
    lines.push("");
  }

  // Trust Mode
  lines.push("## Trust Mode");
  lines.push("");
  lines.push(
    `${trustMode === "trust" ? "🙈 Trust" : "🔍 Checkpoint"} — ` +
    (trustMode === "trust"
      ? "auto-proceed on in-scope issues, auto-fix test failures"
      : "ask before every significant action"),
  );
  lines.push("");

  // Cycle info
  if (plan.cycles.length > 0) {
    lines.push("## 🔄 Circular Dependencies");
    lines.push("");
    for (const cycle of plan.cycles) {
      lines.push(`- ${cycle.join(" → ")}`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*This file is managed by Agent Summoner. Completed tasks are preserved. Update requirements as needed — done tasks will not be removed.*");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate an update for just the todo section of an existing plan file.
 * Used when a phase completes — only the checkboxes change.
 *
 * Returns the updated plan file content.
 */
export function updatePlanFileTodos(existingContent: string): string {
  const ledger = getLedger();
  const files = ledger.files;

  // For each file in the Ledger, find its checkbox in the content and update it
  let updated = existingContent;

  for (const [filePath, entry] of Object.entries(files)) {
    const checked = entry.status === "done" ? "x" : " ";

    // Match: `- [ ] \`filePath\`` or `- [x] \`filePath\``
    const pattern = new RegExp(
      `(- \\[)([ x])(\\] \`${escapeRegex(filePath)}\`)`,
      "g",
    );

    updated = updated.replace(pattern, `$1${checked}$3`);
  }

  // Update timestamp
  const now = new Date().toISOString();
  updated = updated.replace(
    /> Generated by Agent Summoner \| .*/,
    `> Generated by Agent Summoner | ${now} (updated)`,
  );

  return updated;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
